#!/usr/bin/env bash
mkdir testes && cd testes
mkdir doc examples man scripts src
touch doc/README.md examples/my-example-teste.dat man/teste.1 scripts/script-teste.sh src/teste.c

# Conteúdo para o arquivo em doc/
echo "Docs for teste" >> doc/README.md

# Conteúdo para o arquivo em examples/
echo -e '#!/bin/bash\necho "Teste in Bash"\nexit 0' >> examples/my-example-teste.dat

# Conteúdo para o arquivo em man/
echo -e '.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.8.
.TH teste "1" "October 2019" "teste 1.1" "User Commands"
.SH NAME
teste \- Only teste for Autotools.' > man/teste.1

# Conteúdo para o arquivo em scripts/
echo -e '#!/bin/sh\nprintf "Only a teste\\n" "%s"\nexit 0' > scripts/script-teste.sh

# Conteúdo para o arquivo em src/
echo -e '#include <stdio.h>

int main(){
	printf("Only one test for Autotools\\n");
	return 0;
}' > src/teste.c

autoscan
mv configure.scan configure.ac
sed -i 's/FULL-PACKAGE-NAME\],/teste],/g' configure.ac
sed -i 's/VERSION\],/1.0],/g' configure.ac
sed -i 's/BUG-REPORT-ADDRESS\]/teste@terminalroot.com.br]/g' configure.ac
autoconf
echo -e 'AUTOMAKE_OPTIONS = foreign\nSUBDIRS = src doc examples man scripts' > Makefile.am
echo -e '# what flags you want to pass to the C compiler & linker\nCFLAGS = --pedantic -Wall -std=c99 -O2\n# this lists the binaries to produce, the (non-PHONY, binary) targets in\n# the previous manual Makefile\nbin_PROGRAMS = teste\nteste_SOURCES = teste.c' > src/Makefile.am
echo 'man_MANS = teste.1' > man/Makefile.am
echo 'bin_SCRIPTS = script-teste.sh' > scripts/Makefile.am
echo -e 'docdir = $(datadir)/doc/@PACKAGE@\ndoc_DATA = README.md' > doc/Makefile.am
echo -e 'exampledir = $(datarootdir)/doc/@PACKAGE@\nexample_DATA = my-example-teste.dat' > examples/Makefile.am
sed -i '/AC_INIT/{p;s/.*/AM_INIT_AUTOMAKE(teste, 1.0)/;}' configure.ac
sed -i 's@AC_OUTPUT@AC_OUTPUT(Makefile src/Makefile doc/Makefile examples/Makefile man/Makefile scripts/Makefile)@' configure.ac
aclocal
automake --add-missing
autoreconf -fi
autoconf
./configure
make
